-- ============================================================
-- Assignment 10: Car Rental & Fleet Booking System
-- Database Schema for Supabase PostgreSQL
-- ============================================================

-- Drop existing tables if re-running migration (optional)
-- DROP TABLE IF EXISTS rentals;
-- DROP TABLE IF EXISTS vehicles;

-- 1. Vehicles Table
CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
  daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
  fuel_type TEXT NOT NULL,
  seating_capacity INT NOT NULL DEFAULT 5,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE IF NOT EXISTS rentals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- references Supabase auth.users
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_cost NUMERIC(10, 2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- Indexes for performance on collision checks and user lookup
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_dates ON rentals(vehicle_id, start_date, end_date, status);
CREATE INDEX IF NOT EXISTS idx_rentals_user_id ON rentals(user_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_category_status ON vehicles(category, status);

-- Sample Seed Data for Testing (Run if desired)
INSERT INTO vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity, status)
VALUES
  ('Tesla', 'Model 3', 2024, 'Electric', 85.00, 'Electric', 5, 'available'),
  ('Toyota', 'RAV4', 2023, 'SUV', 65.00, 'Hybrid', 5, 'available'),
  ('BMW', '5 Series', 2023, 'Luxury', 120.00, 'Petrol', 5, 'available')
ON CONFLICT DO NOTHING;
